# Generated by Django 4.2 on 2023-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
