# Generated by Django 4.2 on 2023-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_orders_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderupdate",
            name="razor_pay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderupdate",
            name="razor_pay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
